### ISSUE TITLE
Proposal: Run `rbs collection install` before invoking Steep server

### ISSUE THREAD

**Issue by tk0miya** [soutaro/steep-vscode#379]
In real-world development, we frequently switch branches to the main branch, feature branch, etc. I usually restarted the Steep server to let it reload RBS files in the switched branch. And then, I sometimes got a "Run `rbs collection install` to install type definitions" error on restarting Steep.

I usually run `rbs collection install` to resolve the error. I feel it's annoying. How about adding a new option to run `rbs collection install` before invoking Steep server?

**Comment by soutaro** [comment]
I think this should be a feature of Steep itself. Will try to implement this myself.
